export const IMAGE_PATH = {
  home: require('../assets/icons/home.png'),
  debit: require('../assets/icons/debit.png'),
  payments: require('../assets/icons/payments.png'),
  credit: require('../assets/icons/credit.png'),
  profile: require('../assets/icons/profile.png'),
  aspire_logo: require('../assets/icons/aspire_logo.png'),
  eye: require('../assets/icons/eye.png'),
  visa_logo: require('../assets/icons/visa_logo.png'),
  top_up: require('../assets/icons/top_up.png'),
  weekly_limit: require('../assets/icons/weekly_limit.png'),
  freeze: require('../assets/icons/freeze.png'),
  new_debit_card: require('../assets/icons/new_debit_card.png'),
  deactivated_card: require('../assets/icons/deactivated_card.png'),
  back: require('../assets/icons/back.png'),
  pickup_car: require('../assets/icons/pickup_car.png'),
};
