export const SCENE_NAMES = {
  BOTTOM_TAB: 'BOTTOM_TAB',
  BOTTOM_TAB_STACK: {
    HOME: 'STACK_HOME',
    DEBIT_CARD: 'STACK_DEBIT_CARD',
    PAYMENTS: 'STACK_PAYMENTS',
    CREDIT: 'STACK_CREDIT',
    PROFILE: 'STACK_PROFILE',
  },
  WEEKLY_SPENDING_LIMIT: 'WEEKLY_SPENDING_LIMIT',
};
